//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBrightSpotBE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBrightSpotBE.Resources.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスまたはパスワードが間違っています。.
        /// </summary>
        public static string AccoutNotCorrect {
            get {
                return ResourceManager.GetString("AccoutNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウントが存在しません。.
        /// </summary>
        public static string AccoutNotExist {
            get {
                return ResourceManager.GetString("AccoutNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このオプションは使用中のため削除できません。.
        /// </summary>
        public static string CategoryHasMember {
            get {
                return ResourceManager.GetString("CategoryHasMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリーは存在しました。.
        /// </summary>
        public static string CategoryNameExist {
            get {
                return ResourceManager.GetString("CategoryNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリが見つかりません。.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社員コードは既に使用されています。.
        /// </summary>
        public static string CodeExist {
            get {
                return ResourceManager.GetString("CodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会社名は既に存在しています。.
        /// </summary>
        public static string CompanyNameExist {
            get {
                return ResourceManager.GetString("CompanyNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会社が見つかりません。.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属部が不正です。自分と同じ部のみ設定できます。.
        /// </summary>
        public static string DepartmentInvalid {
            get {
                return ResourceManager.GetString("DepartmentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属部が不正です。.
        /// </summary>
        public static string DepartmentNotExist {
            get {
                return ResourceManager.GetString("DepartmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プランを作成するには、「従業員編集」画面の「所属部」項目から部を追加してください。.
        /// </summary>
        public static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属課が不正です。自分と同じ課のみ設定できます。.
        /// </summary>
        public static string DivisionInvalid {
            get {
                return ResourceManager.GetString("DivisionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属課が不正です。.
        /// </summary>
        public static string DivisionNotExist {
            get {
                return ResourceManager.GetString("DivisionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスは既に使用されています。.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスは存在しません。.
        /// </summary>
        public static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雇用形態が不正です。.
        /// </summary>
        public static string EmploymentTypeNotExist {
            get {
                return ResourceManager.GetString("EmploymentTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性別が不正です。.
        /// </summary>
        public static string GenderNotExist {
            get {
                return ResourceManager.GetString("GenderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属グループが不正です。自分と同じグループのみ設定できます。.
        /// </summary>
        public static string GroupInvalid {
            get {
                return ResourceManager.GetString("GroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属グループが不正です。.
        /// </summary>
        public static string GroupNotExist {
            get {
                return ResourceManager.GetString("GroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知が見つかりません。.
        /// </summary>
        public static string NotificatioNotFound {
            get {
                return ResourceManager.GetString("NotificatioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループにまだメンバーがいるために削除できません。.
        /// </summary>
        public static string OrganizationHasMember {
            get {
                return ResourceManager.GetString("OrganizationHasMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部・課・グループの組み合わせが正しくありません。.
        /// </summary>
        public static string OrganizationInvalid {
            get {
                return ResourceManager.GetString("OrganizationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プランが見つかりません。.
        /// </summary>
        public static string PlanNotFound {
            get {
                return ResourceManager.GetString("PlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 役職が不正です。.
        /// </summary>
        public static string PositionNotExist {
            get {
                return ResourceManager.GetString("PositionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクトが見つかりません。.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レポートが見つかりません。.
        /// </summary>
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクセス権限が不正です。自分より下位の権限のみ設定できます。.
        /// </summary>
        public static string RoleInvalid {
            get {
                return ResourceManager.GetString("RoleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクセス権限が不正です。.
        /// </summary>
        public static string RoleNotExist {
            get {
                return ResourceManager.GetString("RoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このオプションは使用中のため削除できません。.
        /// </summary>
        public static string SkillHasMember {
            get {
                return ResourceManager.GetString("SkillHasMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のパスワードの有効期限が切れています。「パスワード再設定画面」でメールアドレスを再度入力して、新しい仮パスワードを取得してください。.
        /// </summary>
        public static string TempPasswordExpired {
            get {
                return ResourceManager.GetString("TempPasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このメールアドレスに送信されました。10分後にもう一度お試しください。.
        /// </summary>
        public static string TempPasswordNoExpired {
            get {
                return ResourceManager.GetString("TempPasswordNoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インポートするレコード数が多すぎます。1回のインポートで100レコード以下にしてください。.
        /// </summary>
        public static string UserImportMax {
            get {
                return ResourceManager.GetString("UserImportMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーが見つかりませんでした。.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザープランアクティビティが見つかりません。.
        /// </summary>
        public static string UserPlanActivityNotFound {
            get {
                return ResourceManager.GetString("UserPlanActivityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メンバーが条件を対応始めたため削除できません。.
        /// </summary>
        public static string UserPlanConditionChanged {
            get {
                return ResourceManager.GetString("UserPlanConditionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザープランが見つかりません。.
        /// </summary>
        public static string UserPlanNotFound {
            get {
                return ResourceManager.GetString("UserPlanNotFound", resourceCulture);
            }
        }
    }
}
