//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBrightSpotBE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBrightSpotBE.Resources.AuthResource", typeof(AuthResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワードと確認用パスワードが一致しません。.
        /// </summary>
        public static string ConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワード（確認用）は64文字以内で入力してください。.
        /// </summary>
        public static string ConfirmPasswordMaxLength {
            get {
                return ResourceManager.GetString("ConfirmPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワード（確認用）を入力してください。.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスは64文字以内で入力してください。.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスが不正です。.
        /// </summary>
        public static string EmailRegx {
            get {
                return ResourceManager.GetString("EmailRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスは必須です。.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワードは64文字以内で入力してください。.
        /// </summary>
        public static string NewPasswordMaxLength {
            get {
                return ResourceManager.GetString("NewPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワードを入力してください。.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードは64文字以内で入力してください。.
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英数大文字、小文字、記号を含めた８桁以上のパスワードを入力してください。.
        /// </summary>
        public static string PasswordRegx {
            get {
                return ResourceManager.GetString("PasswordRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを入力してください。.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テナントの契約期間が終了しました。ご利用を継続される場合は、契約の更新手続きを行ってください。.
        /// </summary>
        public static string TenantExpried {
            get {
                return ResourceManager.GetString("TenantExpried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在、テナントの契約内容を確認中です。アクティベーションが完了次第、ログイン可能となります。.
        /// </summary>
        public static string TenantIsInpreview {
            get {
                return ResourceManager.GetString("TenantIsInpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テナントの利用開始日は {0} です。契約開始までログインはできません。.
        /// </summary>
        public static string TenantIsScheduled {
            get {
                return ResourceManager.GetString("TenantIsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在、テナントのご利用が一時停止されています。詳細は管理者にお問い合わせください。.
        /// </summary>
        public static string TenantIsSuspended {
            get {
                return ResourceManager.GetString("TenantIsSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テナント情報が見つかりません。管理者にお問い合わせください。.
        /// </summary>
        public static string TenantNotFound {
            get {
                return ResourceManager.GetString("TenantNotFound", resourceCulture);
            }
        }
    }
}
