//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBrightSpotBE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBrightSpotBE.Resources.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属部は必須です。.
        /// </summary>
        public static string DepartmentRequired {
            get {
                return ResourceManager.GetString("DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属課は必須です。.
        /// </summary>
        public static string DivisionRequired {
            get {
                return ResourceManager.GetString("DivisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属経験領域は必須です。.
        /// </summary>
        public static string ExperienceAreaRequired {
            get {
                return ResourceManager.GetString("ExperienceAreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属経験分野は必須です。.
        /// </summary>
        public static string ExperienceFieldRequired {
            get {
                return ResourceManager.GetString("ExperienceFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属経験職種は必須です。.
        /// </summary>
        public static string ExperienceJobRequired {
            get {
                return ResourceManager.GetString("ExperienceJobRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称は64文字以内で入力してください。.
        /// </summary>
        public static string NameMaxLenghth {
            get {
                return ResourceManager.GetString("NameMaxLenghth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称は必須です。.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
    }
}
