//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBrightSpotBE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBrightSpotBE.Resources.PlanResource", typeof(PlanResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返信は255文字以内で入力してください。.
        /// </summary>
        public static string CommentMaxLength {
            get {
                return ResourceManager.GetString("CommentMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメントは必要です。.
        /// </summary>
        public static string CommentRequired {
            get {
                return ResourceManager.GetString("CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了日は開始日より後でなければなりません。.
        /// </summary>
        public static string CompleteDateMustBeGreaterThanStartDate {
            get {
                return ResourceManager.GetString("CompleteDateMustBeGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了予定日は必須です。.
        /// </summary>
        public static string CompleteDateRequired {
            get {
                return ResourceManager.GetString("CompleteDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称は64文字以内で入力してください。.
        /// </summary>
        public static string ConditionNameMaxLength {
            get {
                return ResourceManager.GetString("ConditionNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称は必須です。.
        /// </summary>
        public static string ConditionNameRequired {
            get {
                return ResourceManager.GetString("ConditionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 概要は64文字以内で入力してください。.
        /// </summary>
        public static string ConditionOverviewMaxLength {
            get {
                return ResourceManager.GetString("ConditionOverviewMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 概要は必須です。.
        /// </summary>
        public static string ConditionOverviewRequired {
            get {
                return ResourceManager.GetString("ConditionOverviewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 研修プラン説明は64文字以内で入力してください。.
        /// </summary>
        public static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 研修プラン説明は必須です。.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目安時間は1から100の間でなければなりません。.
        /// </summary>
        public static string EsttimeRange {
            get {
                return ResourceManager.GetString("EsttimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目安時間は不正です。.
        /// </summary>
        public static string EsttimeRegx {
            get {
                return ResourceManager.GetString("EsttimeRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目安時間は必須です。.
        /// </summary>
        public static string EsttimeRequired {
            get {
                return ResourceManager.GetString("EsttimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 研修プラン名は64文字以内で入力してください。.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 研修プラン名は必須です。.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始日は必須です。.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメントは255文字以内で入力してください。.
        /// </summary>
        public static string UpdateCommentMaxLength {
            get {
                return ResourceManager.GetString("UpdateCommentMaxLength", resourceCulture);
            }
        }
    }
}
