//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBrightSpotBE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBrightSpotBE.Resources.ProjectResource", typeof(ProjectResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約企業は必須です。.
        /// </summary>
        public static string CompanyIdRequired {
            get {
                return ResourceManager.GetString("CompanyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参画プロジェクト内容は255文字以内で入力してください。.
        /// </summary>
        public static string ContentMaxLength {
            get {
                return ResourceManager.GetString("ContentMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参画プロジェクト内容は必須です。.
        /// </summary>
        public static string ContentRequired {
            get {
                return ResourceManager.GetString("ContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自由記入は255文字以内で入力してください。.
        /// </summary>
        public static string DiscriptionMaxLength {
            get {
                return ResourceManager.GetString("DiscriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDateFormat.
        /// </summary>
        public static string EndDateFormat {
            get {
                return ResourceManager.GetString("EndDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参画終了日は必須です。.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名は64文字以内で入力してください。.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名は必須です。.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参画ポジションは必須です。.
        /// </summary>
        public static string ParticipationPositionRequired {
            get {
                return ResourceManager.GetString("ParticipationPositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参画工程は必須です。.
        /// </summary>
        public static string ParticipationProcessRequired {
            get {
                return ResourceManager.GetString("ParticipationProcessRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDateFormat.
        /// </summary>
        public static string StartDateFormat {
            get {
                return ResourceManager.GetString("StartDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参画開始日は必須です。.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
    }
}
