//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBrightSpotBE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TenantResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenantResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBrightSpotBE.Resources.TenantResource", typeof(TenantResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64文字以内で入力してください。.
        /// </summary>
        public static string BuildingNameMaxLength {
            get {
                return ResourceManager.GetString("BuildingNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このメールアドレスは、システム全体で既に登録されています。別のメールアドレスをご利用ください。.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64文字以内で入力してください。.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスの形式が正しくありません。ご確認ください。.
        /// </summary>
        public static string EmailRegx {
            get {
                return ResourceManager.GetString("EmailRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスは必須です。.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間が不正です。契約開始日は本日以降の日付で、かつ契約終了日より前の日付を指定してください。.
        /// </summary>
        public static string EndDateMustBeAfterStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間は7日以上で設定してください。.
        /// </summary>
        public static string EndDateMustBeAtLeast7DaysAfterStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeAtLeast7DaysAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約終了日は必須です。.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64文字以内で入力してください。.
        /// </summary>
        public static string FirstNameMaxLength {
            get {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者氏名（姓）は必須です。.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64文字以内で入力してください。.
        /// </summary>
        public static string LastNameMaxLength {
            get {
                return ResourceManager.GetString("LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者氏名（名）は必須です。.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64文字以内で入力してください。.
        /// </summary>
        public static string LocalityMaxLength {
            get {
                return ResourceManager.GetString("LocalityMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 市区町村は必須です。.
        /// </summary>
        public static string LocalityRequired {
            get {
                return ResourceManager.GetString("LocalityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業名は64文字以内で入力してください。.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255文字以内で入力してください。.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい契約終了日は、現在の契約開始日以降の日付を指定してください。.
        /// </summary>
        public static string NewEndDateMustBeAfterStartDate {
            get {
                return ResourceManager.GetString("NewEndDateMustBeAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい契約終了日は、本日以降の日付を指定してください。.
        /// </summary>
        public static string NewEndDateMustBeAfterToday {
            get {
                return ResourceManager.GetString("NewEndDateMustBeAfterToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16文字以内で入力してください。.
        /// </summary>
        public static string PhoneMaxLength {
            get {
                return ResourceManager.GetString("PhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号の形式が正しくありません。数字とハイフン(-)のみを入力してください。.
        /// </summary>
        public static string PhoneRegx {
            get {
                return ResourceManager.GetString("PhoneRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号は必須です。.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7文字以内で入力してください。.
        /// </summary>
        public static string PostCodeMaxLength {
            get {
                return ResourceManager.GetString("PostCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号は7桁の半角数字で入力してください。.
        /// </summary>
        public static string PostCodeRegx {
            get {
                return ResourceManager.GetString("PostCodeRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号は必須です。.
        /// </summary>
        public static string PostCodeRequired {
            get {
                return ResourceManager.GetString("PostCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64文字以内で入力してください。.
        /// </summary>
        public static string RegionMaxLength {
            get {
                return ResourceManager.GetString("RegionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 都道府県は必須です。.
        /// </summary>
        public static string RegionRequired {
            get {
                return ResourceManager.GetString("RegionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間が不正です。契約開始日は本日以降の日付で、かつ契約終了日より前の日付を指定してください。.
        /// </summary>
        public static string StartDateMustBeTodayOrLater {
            get {
                return ResourceManager.GetString("StartDateMustBeTodayOrLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約開始日は必須です。.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64文字以内で入力してください。.
        /// </summary>
        public static string StreetMaxLength {
            get {
                return ResourceManager.GetString("StreetMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 町名・番地は必須です。.
        /// </summary>
        public static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
    }
}
