//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBrightSpotBE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBrightSpotBE.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所は64文字以内で入力してください。.
        /// </summary>
        public static string AddressMaxLength {
            get {
                return ResourceManager.GetString("AddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取得日は必須です。.
        /// </summary>
        public static string CertificationDateRequired {
            get {
                return ResourceManager.GetString("CertificationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資格名は必須です。.
        /// </summary>
        public static string CertificationIdRequired {
            get {
                return ResourceManager.GetString("CertificationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社員コードはアルファベット（最大2文字）と数字の組み合わせが必要（最大10桁）.
        /// </summary>
        public static string CodeRegx {
            get {
                return ResourceManager.GetString("CodeRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社員コードは必須です。.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取得・活動日は必須です。.
        /// </summary>
        public static string CompanyAwardDateRequired {
            get {
                return ResourceManager.GetString("CompanyAwardDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社内表彰・活動は必須です。.
        /// </summary>
        public static string CompanyAwardIdRequired {
            get {
                return ResourceManager.GetString("CompanyAwardIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生年月日の形式が正しくありません。YYYY/MM/DDの形式で入力してください。.
        /// </summary>
        public static string DateOfBirthRegx {
            get {
                return ResourceManager.GetString("DateOfBirthRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属部は必須です。.
        /// </summary>
        public static string DepartmentRequired {
            get {
                return ResourceManager.GetString("DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属課は必須です。.
        /// </summary>
        public static string DivisionRequired {
            get {
                return ResourceManager.GetString("DivisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスは64文字以内で入力してください。.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスが不正です。.
        /// </summary>
        public static string EmailRegx {
            get {
                return ResourceManager.GetString("EmailRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスは必須です。.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名（カナ）は64文字以内で入力してください。.
        /// </summary>
        public static string FirstNameKanaMaxLength {
            get {
                return ResourceManager.GetString("FirstNameKanaMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名（カナ）はカタカナで入力してください。.
        /// </summary>
        public static string FirstNameKanaRegx {
            get {
                return ResourceManager.GetString("FirstNameKanaRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名（カナ）は必須です。.
        /// </summary>
        public static string FirstNameKanaRequired {
            get {
                return ResourceManager.GetString("FirstNameKanaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名は64文字以内で入力してください。.
        /// </summary>
        public static string FirstNameMaxLength {
            get {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名は漢字かカタカナで入力してください。.
        /// </summary>
        public static string FirstNameRegx {
            get {
                return ResourceManager.GetString("FirstNameRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名は必須です。.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性別が不正です。.
        /// </summary>
        public static string GenderRegx {
            get {
                return ResourceManager.GetString("GenderRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性別は必須です。.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属グループは必須です。.
        /// </summary>
        public static string GroupRequired {
            get {
                return ResourceManager.GetString("GroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓（カナ）は64文字以内で入力してください。.
        /// </summary>
        public static string LastNameKanaMaxLength {
            get {
                return ResourceManager.GetString("LastNameKanaMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓（カナ）はカタカナで入力してください。.
        /// </summary>
        public static string LastNameKanaRegx {
            get {
                return ResourceManager.GetString("LastNameKanaRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓（カナ）は必須です。.
        /// </summary>
        public static string LastNameKanaRequired {
            get {
                return ResourceManager.GetString("LastNameKanaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓は64文字以内で入力してください。.
        /// </summary>
        public static string LastNameMaxLength {
            get {
                return ResourceManager.GetString("LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓は漢字かカタカナで入力してください。.
        /// </summary>
        public static string LastNameRegx {
            get {
                return ResourceManager.GetString("LastNameRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓は必須です。.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最寄り駅は64文字以内で入力してください。.
        /// </summary>
        public static string NearestStationMaxLength {
            get {
                return ResourceManager.GetString("NearestStationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号は16桁以内で入力してください。.
        /// </summary>
        public static string PhoneMaxLength {
            get {
                return ResourceManager.GetString("PhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号が間違っています。.
        /// </summary>
        public static string PhoneRegx {
            get {
                return ResourceManager.GetString("PhoneRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクセス権限が不正です。 .
        /// </summary>
        public static string RoleRegx {
            get {
                return ResourceManager.GetString("RoleRegx", resourceCulture);
            }
        }
    }
}
